services:
  # 后端服务
  - type: web
    name: draw-lots-backend
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: CLIENT_URL
        fromService:
          type: web
          name: draw-lots-frontend
          property: host

  # 前端服务
  - type: web
    name: draw-lots-frontend
    env: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_BACKEND_URL
        fromService:
          type: web
          name: draw-lots-backend
          property: host
